# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MOTION)		+= motion-core.o
obj-$(CONFIG_MOTION_HELPERS)	+= motion-helpers.o
obj-$(CONFIG_TMC5240)		+= tmc5240.o
obj-$(CONFIG_MOTION_SIMPLE_PWM)	+= simple-pwm.o
